-d C:\Users\MonkPC\workspaces\FPGA\GOWIN\TangNano9K\LushayLabs\ex4\screen_text\impl\gwsynthesis\screen_text.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\MonkPC\workspaces\FPGA\GOWIN\TangNano9K\LushayLabs\ex4\screen_text\constr\pinning_TankPrimer9K.cst
-cfg C:\Users\MonkPC\workspaces\FPGA\GOWIN\TangNano9K\LushayLabs\ex4\screen_text\impl\pnr\device.cfg
-sdc C:\Users\MonkPC\workspaces\FPGA\GOWIN\TangNano9K\LushayLabs\ex4\screen_text\constr\timing_TankPrimer9K.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
